"""create notification table

Revision ID: a338a8c3b8b7
Revises: 
Create Date: 2024-09-01 12:25:28.688176

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a338a8c3b8b7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("issuer_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_customer_id"),
        "notification",
        ["customer_id"],
        unique=False,
    )
    op.create_index(op.f("ix_notification_id"), "notification", ["id"], unique=False)
    op.create_index(
        op.f("ix_notification_issuer_id"), "notification", ["issuer_id"], unique=False
    )
    op.create_index(
        op.f("ix_notification_order_id"), "notification", ["order_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notification_order_id"), table_name="notification")
    op.drop_index(op.f("ix_notification_issuer_id"), table_name="notification")
    op.drop_index(op.f("ix_notification_id"), table_name="notification")
    op.drop_index(op.f("ix_notification_customer_id"), table_name="notification")
    op.drop_table("notification")
    # ### end Alembic commands ###
