"""add shop id column

Revision ID: aeb13785cf19
Revises: a338a8c3b8b7
Create Date: 2024-09-02 10:09:10.562499

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aeb13785cf19"
down_revision: Union[str, None] = "a338a8c3b8b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notification", sa.Column("coffee_shop_id", sa.Integer(), nullable=False)
    )
    op.create_index(
        op.f("ix_notification_coffee_shop_id"),
        "notification",
        ["coffee_shop_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notification_coffee_shop_id"), table_name="notification")
    op.drop_column("notification", "coffee_shop_id")
    # ### end Alembic commands ###
